Feat/section lyubumovka
kur0yuki/lyubimovka pull request #14
Opened 2022-10-15 17:05 UTC by khuseynkhasiev

Создал блок любимовка

2022-10-15 20:40 UTC, kur0yuki requested changes

2022-10-15 20:40 UTC, kur0yuki commented on blocks/lyubimovka/__title/lyubimovka__title.css
> +  font-family: 'Neue Machina', sans-serif;
Шрифт не подключается

2022-10-15 20:40 UTC, kur0yuki commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
При ширине страницы как в макете (1440px) картинка получается 660x445px, в макете 720х445

2022-10-15 20:40 UTC, kur0yuki commented on blocks/lyubimovka/__title/lyubimovka__title.css
> +  font-family: 'Neue Machina', sans-serif;
Попробуй такое название 'Neue Machina Regular'

2022-10-16 11:47 UTC, khuseynkhasiev commented on blocks/lyubimovka/__title/lyubimovka__title.css
> +  font-family: 'Neue Machina', sans-serif;
принял

2022-10-16 11:47 UTC, khuseynkhasiev commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
принял

2022-10-17 22:47 UTC, kur0yuki commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
Тут проблема не в 1fr/auto, а в gap
При ширине экрана 1140px нужно получить одну колонку как 720px (50% экрана), но при gap=120px вместо 50% получается (100% - 120px)/2

2022-10-18 06:03 UTC, khuseynkhasiev commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
Откуда такая информация? Не совсем понимаю о чем речь) Нам же дали размеры на 1440 и под мобилку, а что между ними сказали на наше усмотрение. И так как мы договорились сверстать сначала большой размер, так и делаю. Остальное можно медиа запросами подогнать и убрать если gap будет дальше мешать

2022-10-18 07:28 UTC, kur0yuki commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
Я тоже про размер 1440 говорю

![image](https://user-images.githubusercontent.com/7196973/196363056-a49c40ab-7dd7-4a45-a728-4ee05d938c99.png)
тут картинка 720 + 720 фон

А у тебя сейчас выходит так 780 фон + 660 картинка
![image](https://user-images.githubusercontent.com/7196973/196364647-e4c70d1d-aac6-4093-9659-e6808dcd41f1.png)

2022-10-18 17:27 UTC, khuseynkhasiev commented on blocks/lyubimovka/lyubimovka.css
> +  grid-column-gap: 120px;
При ширине экрана 1140px нужно получить одну колонку .... опечатка в ширине запутала) Отличное объяснение, доработаю

2022-10-18 17:43 UTC, closed without merging